name: Test every month

on:
  schedule:
    - cron: "0 * * * *"
#    - cron: "0 0 1 * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}
